// AUTO-GENERATED - reusable Pixel Lab character library. Assign one of these
// to a new agent (or person). Static assets under public/character-library/.
// Do not edit by hand — regenerate with scripts/characters/build_library.py.

export type Dir = "south"|"east"|"north"|"west"|"south-east"|"north-east"|"north-west"|"south-west";
export interface LibChar {
  id: string; gender: string; role: string; description: string;
  portrait: string; standing: Partial<Record<Dir, string>>;
  seated?: string; working?: string; workingFrames?: number;
  sleeping?: string;
  breathing?: Partial<Record<Dir, string>>; breathingFrames?: number; }

export const CHARACTER_LIBRARY: Record<string, LibChar> = {
  "designer-f": {"id": "designer-f", "gender": "female", "role": "designer", "description": "a female product designer in a mustard beanie and denim jacket, small wireless earbuds, teal-dyed shoulder-length hair, olive skin", "portrait": "/character-library/designer-f/standing/south.png", "standing": {"south": "/character-library/designer-f/standing/south.png", "east": "/character-library/designer-f/standing/east.png", "north": "/character-library/designer-f/standing/north.png", "west": "/character-library/designer-f/standing/west.png", "south-east": "/character-library/designer-f/standing/south-east.png", "north-east": "/character-library/designer-f/standing/north-east.png", "north-west": "/character-library/designer-f/standing/north-west.png", "south-west": "/character-library/designer-f/standing/south-west.png"}, "seated": "/character-library/designer-f/seated.png", "working": "/character-library/designer-f/working.png", "workingFrames": 9, "sleeping": "/character-library/designer-f/sleeping.png", "breathing": {"south": "/character-library/designer-f/breathing/south.png", "north": "/character-library/designer-f/breathing/north.png"}, "breathingFrames": 9},
  "designer-m": {"id": "designer-m", "gender": "male", "role": "designer", "description": "a male UX designer in a cream knit sweater, round glasses, tidy blond hair, fair skin", "portrait": "/character-library/designer-m/standing/south.png", "standing": {"south": "/character-library/designer-m/standing/south.png", "east": "/character-library/designer-m/standing/east.png", "north": "/character-library/designer-m/standing/north.png", "west": "/character-library/designer-m/standing/west.png", "south-east": "/character-library/designer-m/standing/south-east.png", "north-east": "/character-library/designer-m/standing/north-east.png", "north-west": "/character-library/designer-m/standing/north-west.png", "south-west": "/character-library/designer-m/standing/south-west.png"}, "seated": "/character-library/designer-m/seated.png", "working": "/character-library/designer-m/working.png", "workingFrames": 9, "sleeping": "/character-library/designer-m/sleeping.png", "breathing": {"south": "/character-library/designer-m/breathing/south.png", "north": "/character-library/designer-m/breathing/north.png"}, "breathingFrames": 9},
  "engineer-f": {"id": "engineer-f", "gender": "female", "role": "engineer", "description": "a female software engineer in a grey zip hoodie wearing over-ear headphones, curly auburn hair, fair freckled skin", "portrait": "/character-library/engineer-f/standing/south.png", "standing": {"south": "/character-library/engineer-f/standing/south.png", "east": "/character-library/engineer-f/standing/east.png", "north": "/character-library/engineer-f/standing/north.png", "west": "/character-library/engineer-f/standing/west.png", "south-east": "/character-library/engineer-f/standing/south-east.png", "north-east": "/character-library/engineer-f/standing/north-east.png", "north-west": "/character-library/engineer-f/standing/north-west.png", "south-west": "/character-library/engineer-f/standing/south-west.png"}, "seated": "/character-library/engineer-f/seated.png", "working": "/character-library/engineer-f/working.png", "workingFrames": 9, "sleeping": "/character-library/engineer-f/sleeping.png", "breathing": {"south": "/character-library/engineer-f/breathing/south.png", "north": "/character-library/engineer-f/breathing/north.png"}, "breathingFrames": 9},
  "engineer-m": {"id": "engineer-m", "gender": "male", "role": "engineer", "description": "a male software developer in a black hoodie with a slim headset mic, dark-framed glasses, short black hair, medium brown skin", "portrait": "/character-library/engineer-m/standing/south.png", "standing": {"south": "/character-library/engineer-m/standing/south.png", "east": "/character-library/engineer-m/standing/east.png", "north": "/character-library/engineer-m/standing/north.png", "west": "/character-library/engineer-m/standing/west.png", "south-east": "/character-library/engineer-m/standing/south-east.png", "north-east": "/character-library/engineer-m/standing/north-east.png", "north-west": "/character-library/engineer-m/standing/north-west.png", "south-west": "/character-library/engineer-m/standing/south-west.png"}, "seated": "/character-library/engineer-m/seated.png", "working": "/character-library/engineer-m/working.png", "workingFrames": 9, "sleeping": "/character-library/engineer-m/sleeping.png", "breathing": {"south": "/character-library/engineer-m/breathing/south.png", "north": "/character-library/engineer-m/breathing/north.png"}, "breathingFrames": 9},
  "exec-f": {"id": "exec-f", "gender": "female", "role": "executive", "description": "a confident female executive in a charcoal business suit with a silk blouse, gold stud earrings, sleek black hair in a low bun, warm brown skin", "portrait": "/character-library/exec-f/standing/south.png", "standing": {"south": "/character-library/exec-f/standing/south.png", "east": "/character-library/exec-f/standing/east.png", "north": "/character-library/exec-f/standing/north.png", "west": "/character-library/exec-f/standing/west.png", "south-east": "/character-library/exec-f/standing/south-east.png", "north-east": "/character-library/exec-f/standing/north-east.png", "north-west": "/character-library/exec-f/standing/north-west.png", "south-west": "/character-library/exec-f/standing/south-west.png"}, "seated": "/character-library/exec-f/seated.png", "working": "/character-library/exec-f/working.png", "workingFrames": 9, "sleeping": "/character-library/exec-f/sleeping.png", "breathing": {"south": "/character-library/exec-f/breathing/south.png", "north": "/character-library/exec-f/breathing/north.png"}, "breathingFrames": 9},
  "exec-m": {"id": "exec-m", "gender": "male", "role": "executive", "description": "a confident male CEO in a navy three-piece suit and tie, silver wristwatch, neat salt-and-pepper hair, light skin", "portrait": "/character-library/exec-m/standing/south.png", "standing": {"south": "/character-library/exec-m/standing/south.png", "east": "/character-library/exec-m/standing/east.png", "north": "/character-library/exec-m/standing/north.png", "west": "/character-library/exec-m/standing/west.png", "south-east": "/character-library/exec-m/standing/south-east.png", "north-east": "/character-library/exec-m/standing/north-east.png", "north-west": "/character-library/exec-m/standing/north-west.png", "south-west": "/character-library/exec-m/standing/south-west.png"}, "seated": "/character-library/exec-m/seated.png", "working": "/character-library/exec-m/working.png", "workingFrames": 9, "sleeping": "/character-library/exec-m/sleeping.png", "breathing": {"south": "/character-library/exec-m/breathing/south.png", "north": "/character-library/exec-m/breathing/north.png"}, "breathingFrames": 9},
  "sales-f": {"id": "sales-f", "gender": "female", "role": "sales", "description": "a female sales lead in a burgundy blazer over a white top, small hoop earrings, straight shoulder-length brown hair, tan skin, full body standing character shown head to toe, small character sprite", "portrait": "/character-library/sales-f/standing/south.png", "standing": {"south": "/character-library/sales-f/standing/south.png", "east": "/character-library/sales-f/standing/east.png", "north": "/character-library/sales-f/standing/north.png", "west": "/character-library/sales-f/standing/west.png", "south-east": "/character-library/sales-f/standing/south-east.png", "north-east": "/character-library/sales-f/standing/north-east.png", "north-west": "/character-library/sales-f/standing/north-west.png", "south-west": "/character-library/sales-f/standing/south-west.png"}, "seated": "/character-library/sales-f/seated.png", "working": "/character-library/sales-f/working.png", "workingFrames": 9, "sleeping": "/character-library/sales-f/sleeping.png", "breathing": {"south": "/character-library/sales-f/breathing/south.png", "north": "/character-library/sales-f/breathing/north.png"}, "breathingFrames": 9},
  "sales-m": {"id": "sales-m", "gender": "male", "role": "sales", "description": "a male salesperson in a light-blue dress shirt and navy tie with a bluetooth earpiece, neat black hair, dark brown skin", "portrait": "/character-library/sales-m/standing/south.png", "standing": {"south": "/character-library/sales-m/standing/south.png", "east": "/character-library/sales-m/standing/east.png", "north": "/character-library/sales-m/standing/north.png", "west": "/character-library/sales-m/standing/west.png", "south-east": "/character-library/sales-m/standing/south-east.png", "north-east": "/character-library/sales-m/standing/north-east.png", "north-west": "/character-library/sales-m/standing/north-west.png", "south-west": "/character-library/sales-m/standing/south-west.png"}, "seated": "/character-library/sales-m/seated.png", "working": "/character-library/sales-m/working.png", "workingFrames": 9, "sleeping": "/character-library/sales-m/sleeping.png", "breathing": {"south": "/character-library/sales-m/breathing/south.png", "north": "/character-library/sales-m/breathing/north.png"}, "breathingFrames": 9},
};

export const LIBRARY_IDS = Object.keys(CHARACTER_LIBRARY);
