// AUTO-GENERATED - Pixel Lab seated office cast (create_character_state +
// breathing-idle). Static assets under public/characters-seated/. Do not edit.

export type Dir = "south"|"east"|"north"|"west"|"south-east"|"north-east"|"north-west"|"south-west";
export interface OfficeChar { seated: string; working?: string;
  workingFrames?: number; sleeping?: string;
  standing?: Partial<Record<Dir, string>> }

export const OFFICE_CAST: Record<string, OfficeChar> = {
  "orchestrator": {"seated": "/characters-seated/orchestrator/seated.png", "working": "/characters-seated/orchestrator/working.png", "workingFrames": 9, "sleeping": "/characters-seated/orchestrator/sleeping.png", "standing": {"south": "/characters-seated/orchestrator/standing/south.png", "east": "/characters-seated/orchestrator/standing/east.png", "north": "/characters-seated/orchestrator/standing/north.png", "west": "/characters-seated/orchestrator/standing/west.png", "south-east": "/characters-seated/orchestrator/standing/south-east.png", "north-east": "/characters-seated/orchestrator/standing/north-east.png", "north-west": "/characters-seated/orchestrator/standing/north-west.png", "south-west": "/characters-seated/orchestrator/standing/south-west.png"}},
  "apis-config": {"seated": "/characters-seated/apis-config/seated.png", "working": "/characters-seated/apis-config/working.png", "workingFrames": 9, "sleeping": "/characters-seated/apis-config/sleeping.png", "standing": {"south": "/characters-seated/apis-config/standing/south.png", "east": "/characters-seated/apis-config/standing/east.png", "north": "/characters-seated/apis-config/standing/north.png", "west": "/characters-seated/apis-config/standing/west.png", "south-east": "/characters-seated/apis-config/standing/south-east.png", "north-east": "/characters-seated/apis-config/standing/north-east.png", "north-west": "/characters-seated/apis-config/standing/north-west.png", "south-west": "/characters-seated/apis-config/standing/south-west.png"}},
  "sales": {"seated": "/characters-seated/sales/seated.png", "working": "/characters-seated/sales/working.png", "workingFrames": 9, "sleeping": "/characters-seated/sales/sleeping.png", "standing": {"south": "/characters-seated/sales/standing/south.png", "east": "/characters-seated/sales/standing/east.png", "north": "/characters-seated/sales/standing/north.png", "west": "/characters-seated/sales/standing/west.png", "south-east": "/characters-seated/sales/standing/south-east.png", "north-east": "/characters-seated/sales/standing/north-east.png", "north-west": "/characters-seated/sales/standing/north-west.png", "south-west": "/characters-seated/sales/standing/south-west.png"}},
  "task-manager": {"seated": "/characters-seated/task-manager/seated.png", "working": "/characters-seated/task-manager/working.png", "workingFrames": 9, "sleeping": "/characters-seated/task-manager/sleeping.png", "standing": {"south": "/characters-seated/task-manager/standing/south.png", "east": "/characters-seated/task-manager/standing/east.png", "north": "/characters-seated/task-manager/standing/north.png", "west": "/characters-seated/task-manager/standing/west.png", "south-east": "/characters-seated/task-manager/standing/south-east.png", "north-east": "/characters-seated/task-manager/standing/north-east.png", "north-west": "/characters-seated/task-manager/standing/north-west.png", "south-west": "/characters-seated/task-manager/standing/south-west.png"}},
  "email-assistant": {"seated": "/characters-seated/email-assistant/seated.png", "working": "/characters-seated/email-assistant/working.png", "workingFrames": 9, "sleeping": "/characters-seated/email-assistant/sleeping.png", "standing": {"south": "/characters-seated/email-assistant/standing/south.png", "east": "/characters-seated/email-assistant/standing/east.png", "north": "/characters-seated/email-assistant/standing/north.png", "west": "/characters-seated/email-assistant/standing/west.png", "south-east": "/characters-seated/email-assistant/standing/south-east.png", "north-east": "/characters-seated/email-assistant/standing/north-east.png", "north-west": "/characters-seated/email-assistant/standing/north-west.png", "south-west": "/characters-seated/email-assistant/standing/south-west.png"}},
  "reconciler": {"seated": "/characters-seated/reconciler/seated.png", "working": "/characters-seated/reconciler/working.png", "workingFrames": 9, "sleeping": "/characters-seated/reconciler/sleeping.png", "standing": {"south": "/characters-seated/reconciler/standing/south.png", "east": "/characters-seated/reconciler/standing/east.png", "north": "/characters-seated/reconciler/standing/north.png", "west": "/characters-seated/reconciler/standing/west.png", "south-east": "/characters-seated/reconciler/standing/south-east.png", "north-east": "/characters-seated/reconciler/standing/north-east.png", "north-west": "/characters-seated/reconciler/standing/north-west.png", "south-west": "/characters-seated/reconciler/standing/south-west.png"}},
  "delivery": {"seated": "/characters-seated/delivery/seated.png", "working": "/characters-seated/delivery/working.png", "workingFrames": 9, "sleeping": "/characters-seated/delivery/sleeping.png", "standing": {"south": "/characters-seated/delivery/standing/south.png", "east": "/characters-seated/delivery/standing/east.png", "north": "/characters-seated/delivery/standing/north.png", "west": "/characters-seated/delivery/standing/west.png", "south-east": "/characters-seated/delivery/standing/south-east.png", "north-east": "/characters-seated/delivery/standing/north-east.png", "north-west": "/characters-seated/delivery/standing/north-west.png", "south-west": "/characters-seated/delivery/standing/south-west.png"}},
  "billing": {"seated": "/characters-seated/billing/seated.png", "working": "/characters-seated/billing/working.png", "workingFrames": 9, "sleeping": "/characters-seated/billing/sleeping.png", "standing": {"south": "/characters-seated/billing/standing/south.png", "east": "/characters-seated/billing/standing/east.png", "north": "/characters-seated/billing/standing/north.png", "west": "/characters-seated/billing/standing/west.png", "south-east": "/characters-seated/billing/standing/south-east.png", "north-east": "/characters-seated/billing/standing/north-east.png", "north-west": "/characters-seated/billing/standing/north-west.png", "south-west": "/characters-seated/billing/standing/south-west.png"}},
  "strategy": {"seated": "/characters-seated/strategy/seated.png", "working": "/characters-seated/strategy/working.png", "workingFrames": 9, "sleeping": "/characters-seated/strategy/sleeping.png", "standing": {"south": "/characters-seated/strategy/standing/south.png", "east": "/characters-seated/strategy/standing/east.png", "north": "/characters-seated/strategy/standing/north.png", "west": "/characters-seated/strategy/standing/west.png", "south-east": "/characters-seated/strategy/standing/south-east.png", "north-east": "/characters-seated/strategy/standing/north-east.png", "north-west": "/characters-seated/strategy/standing/north-west.png", "south-west": "/characters-seated/strategy/standing/south-west.png"}},
};
