-- Mem0 episodic memory schema (WBS 2.5, mem0ai >= 2.x)
--
-- In mem0ai 2.x the pgvector provider creates the table automatically.
-- This file is for reference only — run DROP TABLE IF EXISTS mem0_memories
-- to let Mem0 recreate it with the correct column names on next init.
-- 
-- Legacy (mem0ai 1.x): column was "embedding VECTOR(1536)"
-- Current (mem0ai 2.x): column is "vector", table created by Mem0 itself
