#!/usr/bin/env python3
"""Generate the observability Office role-sprite cast with Pixel Lab.

Regenerates `src/app/observability/sprites.generated.ts` — one transparent,
waist-up pixel-art bust per role (coder / sales / planner / triage / reconciler /
orchestrator / default), matched to the `scene.tsx` PRESETS (outfit + accessory).
Embeds each as a data-URI so the office is CSP-safe (no external asset host).

Usage:
    PIXELLAB_API_KEY=... python scripts/gen_office_sprites.py

Requires `pillow` (for transparent-margin trimming) and network access to
`api.pixellab.ai`. Each sprite costs one Pixel Lab generation. Validate the
result (the office renders them directly) before committing.

Per-agent CUSTOM sprites are generated at runtime by the Avatar Studio via the
gateway `POST /observability/avatars/generate` endpoint — this script only bakes
the default per-role cast that ships in the bundle.
"""
from __future__ import annotations

import base64
import io
import json
import os
import sys
import time
import urllib.request
from pathlib import Path

from PIL import Image  # type: ignore

API = "https://api.pixellab.ai/v1/generate-image-pixflux"
OUT_TS = Path(__file__).resolve().parents[1] / "src/app/observability/sprites.generated.ts"

STYLE = (
    "cute chibi pixel art office worker, seated at a desk, waist up, facing "
    "forward, symmetrical, clean dark outline, soft shading, friendly "
    "expression, centered"
)

# role → subject; matches scene.tsx PRESETS so the cast reads consistently.
ROLES: dict[str, str] = {
    "coder": "developer wearing a blue hoodie and a headset",
    "sales": "salesperson wearing a dark navy business suit and a headset",
    "planner": "planner wearing a warm red sweater and round glasses",
    "triage": "support agent wearing a green hoodie",
    "reconciler": "accountant wearing a grey sweater and glasses",
    "orchestrator": "team leader wearing a purple suit and a headset",
    "default": "office worker wearing a grey sweater",
}


def generate(subject: str, seed: int) -> bytes:
    body = {
        "description": f"{subject}, {STYLE}",
        "image_size": {"width": 200, "height": 200},
        "no_background": True,
        "text_guidance_scale": 7.5,
        "seed": seed,
    }
    req = urllib.request.Request(
        API,
        data=json.dumps(body).encode(),
        headers={"Authorization": f"Bearer {KEY}", "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=180) as r:
        data = json.loads(r.read().decode())
    raw = data["image"]["base64"].split(",")[-1]
    return base64.b64decode(raw)


def trim_bottom_anchored(png: bytes) -> Image.Image:
    """Crop transparent margins, pad to a square, bottom-anchored (busts sit low)."""
    im = Image.open(io.BytesIO(png)).convert("RGBA")
    box = im.getbbox()
    if box:
        im = im.crop(box)
    w, h = im.size
    s = max(w, h) + 8
    canvas = Image.new("RGBA", (s, s), (0, 0, 0, 0))
    canvas.alpha_composite(im, ((s - w) // 2, s - h))
    return canvas


def data_uri(im: Image.Image) -> str:
    buf = io.BytesIO()
    im.save(buf, format="PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def main() -> int:
    uris: dict[str, str] = {}
    for i, (role, subject) in enumerate(ROLES.items()):
        for attempt in range(3):
            try:
                print(f"[{role}] generating…", flush=True)
                im = trim_bottom_anchored(generate(subject, seed=1000 + i))
                uris[role] = data_uri(im)
                print(f"[{role}] ok {im.size}", flush=True)
                break
            except Exception as e:  # noqa: BLE001
                print(f"[{role}] attempt {attempt + 1} failed: {e}", flush=True)
                time.sleep(3)
        else:
            print(f"[{role}] FAILED — aborting so the module stays consistent", file=sys.stderr)
            return 1

    lines = [
        "// AUTO-GENERATED by scripts/gen_office_sprites.py — do not edit by hand.",
        "// Real pixel-art office cast generated with Pixel Lab (pixflux, transparent",
        "// background, waist-up bust per role). Embedded as data-URIs so they are",
        "// CSP-safe everywhere (no external asset host). Regenerate with the script.",
        "//",
        "// Each key is a role from scene.tsx `roleFor()` → a bottom-anchored,",
        "// transparent PNG bust that drops into the AgentScene character slot.",
        "",
        "export const ROLE_SPRITES: Record<string, string> = {",
        *[f'  {role}: "{uris[role]}",' for role in ROLES],
        "};",
        "",
        "/** True if a real sprite exists for this role key. */",
        "export function hasRoleSprite(role: string): boolean {",
        "  return Object.prototype.hasOwnProperty.call(ROLE_SPRITES, role);",
        "}",
        "",
    ]
    OUT_TS.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT_TS}")
    return 0


if __name__ == "__main__":
    KEY = os.environ.get("PIXELLAB_API_KEY", "").strip()
    if not KEY:
        print("PIXELLAB_API_KEY is not set", file=sys.stderr)
        sys.exit(1)
    sys.exit(main())
