/**
 * POST /api/agent/chat
 *
 * Returns a Server-Sent Events stream so the UI can render tokens and
 * tool-call events in real time (mirroring the VS Code Copilot experience).
 *
 * IMPORTANT — Three distinct runtimes; do not conflate:
 *
 *   mode="copilot"   → GitHub Copilot SDK runtime (apps/gateway/routes/copilot_chat.py)
 *                       - CopilotClient wraps `gh copilot` CLI as a subprocess
 *                       - autopilot mode: native tool-calling (shell, file r/w, Python)
 *                       - reads AGENTS.md / .mcp.json from agent workspace
 *                       - on_pre_tool_use / on_post_tool_use hooks emit tool_start/tool_end SSE
 *                       - Auth: GITHUB_TOKEN (direct to api.githubcopilot.com)
 *                              OR BYOK via LiteLLM (session_kwargs["provider"])
 *                       - NOT the same as CopilotKit (the React UI library)
 *
 *   mode="litellm"   → Direct LiteLLM streaming (no orchestration, no tool calling)
 *                       - Raw OpenAI-compatible /chat/completions call
 *                       - Model = tier1/2/3 alias in infra/litellm/config.yaml
 *                       - Used for fast text-only responses
 *
 *   mode="langgraph" → Legacy LangGraph agent runner (batch, no streaming)
 *                       - POST /agent/run on FastAPI gateway
 *                       - Returns single delta+done pair (not streamed)
 *                       - Future: replace with /agent/langgraph streaming endpoint
 *
 * SSE event types:
 *   {"type":"delta",      "content":"…"}
 *   {"type":"reasoning",  "content":"…"}              — model chain-of-thought (reasoning models only)
 *   {"type":"progress",   "name":"…"}                  — tool about to run (live status)
 *   {"type":"tool_start", "id":"…","name":"…","args":{}}
 *   {"type":"tool_end",   "id":"…","name":"…","result":"…","success":bool}
 *   {"type":"done",       "run_id":"…"}
 *   {"type":"error",      "content":"…"}
 */

import { NextRequest } from "next/server";
import { auth } from "@/auth";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export interface ChatMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

interface ChatRequest {
  agentName: string;
  message: string;
  messages: ChatMessage[];
  threadId: string;
  mode?: "langgraph" | "copilot" | "litellm";
  /** Copilot SDK model override forwarded to gateway (e.g. "claude-sonnet-4.5"). */
  model?: string;
  /** System-level context (persistent memory / persona) injected as context. */
  context?: string;
  /** Thinking mode: "auto" | "thinking" | "max" */
  thinkMode?: string;
  /** Assistant message ID generated by the frontend.  Used so server-side
   *  persistence writes to the SAME row the frontend renders, enabling
   *  reliable refresh recovery. */
  assistantMessageId?: string;
  /** Last SSE event ID the client received before disconnecting.  Sent on
   *  reconnect so the server can replay only missed events. */
  lastEventId?: string;
  /** When true, the client is reconnecting to an existing agent run rather
   *  than starting a new one.  The route calls the reconnect endpoint. */
  reconnect?: boolean;
}

const GATEWAY_URL = process.env.GATEWAY_BASE_URL ?? "http://127.0.0.1:8000";
const LITELLM_BASE_URL =
  process.env.COPILOT_LLM_BASE_URL ?? process.env.LITELLM_BASE_URL ?? "http://127.0.0.1:8080/v1";
const LITELLM_KEY =
  process.env.LITELLM_MASTER_KEY ?? process.env.GATEWAY_INTERNAL_TOKEN ?? "sk-local-dev-change-me";
const INTERNAL_TOKEN =
  process.env.GATEWAY_INTERNAL_TOKEN ?? process.env.LITELLM_MASTER_KEY ?? "sk-local-dev-change-me";

// ─── Message persistence during streaming ──────────────────────────────────

/**
 * Save the accumulated assistant message to Postgres so it survives client
 * disconnect (tab close, browser quit, network drop). Called periodically
 * during streaming and once when the stream completes.
 *
 * Persists content, tool events, reasoning blocks, and progress lines so
 * the polling recovery path can restore the full stream state (thinking
 * cascade, tool progress, etc.) — not just the final text.
 */
async function persistAssistantMessage(
  threadId: string,
  content: string,
  toolEvents: Array<Record<string, unknown>> = [],
  reasoningBlocks: string[] = [],
  progressLines: string[] = [],
  messageId?: string,
): Promise<void> {
  if (!content.trim() && toolEvents.length === 0 && reasoningBlocks.length === 0) return;
  try {
    const payload = [{
      // Use the frontend-supplied message ID so the row correlates with the
      // message the browser renders (enables refresh recovery).  Fall back to
      // a per-thread id only when the frontend didn't supply one.
      id: messageId || `assistant-${threadId}`,
      role: "assistant",
      content,
      timestamp: Date.now(),
      tool_events: toolEvents,
      progress_lines: progressLines,
      reasoning: reasoningBlocks.length > 0 ? reasoningBlocks.join("\n---\n") : null,
      agent_state: null,
      custom_events: [],
    }];
    // Write directly to the gateway's chat message store so messages survive
    // even if the Next.js process restarts mid-stream.
    await fetch(
      `${GATEWAY_URL}/chat/sessions/${threadId}/messages`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${INTERNAL_TOKEN}`,
        },
        body: JSON.stringify(payload),
        signal: AbortSignal.timeout(5000),
      }
    );
  } catch {
    // Best-effort: don't break the stream for persistence failures
  }
}

/**
 * Translate AG-UI events from the backend into our SSE format, persisting
 * the accumulated assistant message to Postgres along the way so the
 * conversation survives client disconnects.
 *
 * Returns the accumulated assistant content for final persistence.
 */
async function translateAndPersistStream(
  agUiBody: ReadableStream<Uint8Array>,
  controller: ReadableStreamDefaultController<Uint8Array>,
  threadId: string,
  assistantMessageId?: string,
): Promise<string> {
  const reader = agUiBody.getReader();
  const decoder = new TextDecoder();
  const toolNames: Record<string, string> = {};
  const toolArgs: Record<string, string> = {};
  const toolEvents: Array<Record<string, unknown>> = [];
  /** Accumulated reasoning blocks (model chain-of-thought).  Each complete
   *  sentence / paragraph becomes a separate block for the UI cascade. */
  const reasoningBlocks: string[] = [];
  /** Brief progress snippets shown in the ThinkingContainer header. */
  const progressLines: string[] = [];
  let buf = "";
  let assistantContent = "";
  let lastPersistTime = Date.now();
  let clientConnected = true;

  /** Safely enqueue to the client; sets clientConnected=false on failure. */
  const enqueue = (data: Record<string, unknown>) => {
    if (!clientConnected) return;
    try {
      controller.enqueue(
        new TextEncoder().encode(`data: ${JSON.stringify(data)}\n\n`)
      );
    } catch {
      clientConnected = false;
    }
  };

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += decoder.decode(value, { stream: true });
      const lines = buf.split("\n");
      buf = lines.pop() ?? "";
      for (const line of lines) {
        if (!line.startsWith("data: ")) continue;
        const raw = line.slice(6).trim();
        if (!raw) continue;
        let ev: Record<string, unknown>;
        try { ev = JSON.parse(raw); } catch { continue; }
        const t = ev.type as string;
        let out: Record<string, unknown> | null = null;

        if (t === "TEXT_MESSAGE_CONTENT") {
          const delta = String(ev.delta ?? "");
          assistantContent += delta;
          out = { type: "delta", content: delta };
        } else if (t === "REASONING_MESSAGE_CONTENT" || t === "THINKING_TEXT_MESSAGE_CONTENT") {
          const chunk = String(ev.delta ?? "");
          if (chunk) {
            // Group verbose reasoning into paragraph blocks (split on \n\n),
            // mirroring the frontend cascade logic.
            if (reasoningBlocks.length === 0) {
              reasoningBlocks.push(chunk);
            } else {
              const merged = reasoningBlocks[reasoningBlocks.length - 1] + chunk;
              const parts = merged.split(/\n{2,}/).filter((p, i, a) => p.trim() || i === a.length - 1);
              reasoningBlocks.splice(reasoningBlocks.length - 1, 1, ...parts);
            }
          }
          out = { type: "reasoning", content: ev.delta ?? "" };
        } else if (t === "PROGRESS_UPDATE") {
          // Tool progress / partial output — shown in the thinking header,
          // never in the visible assistant message.
          const msg = String(ev.message ?? "");
          if (msg) {
            progressLines.push(msg);
            if (progressLines.length > 20) progressLines.shift();
          }
          out = { type: "progress", name: msg };
        } else if (t === "TODO_LIST") {
          // Structured todo list (VS Code Todos panel parity).
          out = { type: "todos", todos: ev.todos ?? [] };
        } else if (t === "TOOL_CALL_START") {
          const name = String(ev.toolCallName ?? ev.tool_call_name ?? "tool");
          toolNames[String(ev.toolCallId ?? "")] = name;
          toolArgs[String(ev.toolCallId ?? "")] = "";
          // VS Code-style narration fold (mirror of the frontend): text
          // accumulated before a tool call is plan narration, not the
          // answer — persist it as a reasoning block instead.
          if (assistantContent.trim()) {
            reasoningBlocks.push(assistantContent.trim());
            assistantContent = "";
          }
          // Capture progress so the polling recovery path can show tool activity.
          progressLines.push(name);
          if (progressLines.length > 20) progressLines.shift();
          enqueue({ type: "progress", name });
          out = { type: "tool_start", id: ev.toolCallId, name, args: {} };
        } else if (t === "TOOL_CALL_ARGS") {
          const id = String(ev.toolCallId ?? "");
          toolArgs[id] = (toolArgs[id] ?? "") + String(ev.delta ?? "");
        } else if (t === "TOOL_CALL_END" || t === "TOOL_CALL_RESULT") {
          const id = String(ev.toolCallId ?? "");
          const name = toolNames[id] ?? "tool";
          const result = String(ev.result ?? ev.content ?? "");
          toolEvents.push({
            id, name,
            args: parseToolArgs(toolArgs[id]),
            result,
            status: "done",
          });
          out = {
            type: "tool_end", id: ev.toolCallId, name,
            args: parseToolArgs(toolArgs[id]),
            result, success: true,
          };
        } else if (t === "STATE_SNAPSHOT") {
          out = { type: "state", snapshot: ev.snapshot ?? {} };
        } else if (t === "STATE_DELTA") {
          out = { type: "state_delta", delta: ev.delta ?? [] };
        } else if (t === "CUSTOM") {
          out = { type: "custom", name: ev.name ?? "", value: ev.value ?? null };
        } else if (t === "SUB_AGENT_TEXT_DELTA") {
          out = { type: "sub_agent_delta", agentName: String(ev.agentName ?? ""), runId: String(ev.runId ?? ""), delta: String(ev.delta ?? "") };
        } else if (t === "SUB_AGENT_TOOL_CALL_START") {
          out = { type: "sub_agent_tool_start", agentName: String(ev.agentName ?? ""), id: String(ev.toolCallId ?? ""), name: String(ev.toolCallName ?? "") };
        } else if (t === "SUB_AGENT_TOOL_CALL_RESULT") {
          out = { type: "sub_agent_tool_end", agentName: String(ev.agentName ?? ""), id: String(ev.toolCallId ?? ""), result: String(ev.content ?? ""), success: ev.success !== false };
        } else if (t === "SUB_AGENT_ERROR") {
          out = { type: "sub_agent_error", agentName: String(ev.agentName ?? ""), error: String(ev.error ?? "Sub-agent error") };
        } else if (t === "RUN_FINISHED" || t === "done") {
          // RUN_FINISHED: standard AG-UI event from the agent executor.
          // "done": synthetic event from the reconnect endpoint when the
          // agent has already finished (Redis stream expired or empty).
          out = { type: "done", run_id: ev.runId || ev.run_id };
        } else if (t === "RUN_ERROR") {
          out = { type: "error", content: String(ev.message ?? "Agent run error") };
        }

        // Forward the Redis stream ID so the frontend can track the last
        // event it received — enables precise reconnection after disconnect.
        if (out && ev._stream_id) {
          out._stream_id = ev._stream_id;
        }

        if (out) enqueue(out);

        // Persist every 3s while streaming, so messages survive client disconnect.
        // Include reasoning blocks and progress lines so the polling recovery
        // path can restore the full stream state (thinking cascade, tool
        // progress, etc.) — not just the final text.
        const now = Date.now();
        if ((assistantContent.trim() || reasoningBlocks.length > 0) && now - lastPersistTime > 3000) {
          lastPersistTime = now;
          persistAssistantMessage(threadId, assistantContent, toolEvents, reasoningBlocks, progressLines, assistantMessageId).catch(() => {});
        }
      }
    }
  } catch {
    // Backend stream ended early
  }

  // Final persist — ensure the complete message is saved with all stream metadata.
  if (assistantContent.trim() || toolEvents.length > 0 || reasoningBlocks.length > 0) {
    await persistAssistantMessage(threadId, assistantContent, toolEvents, reasoningBlocks, progressLines, assistantMessageId).catch(() => {});
  }

  if (clientConnected) {
    try { controller.close(); } catch { /* already closed */ }
  }

  return assistantContent;
}

/** EXECUTIVE_EMAILS: comma-separated list of executive emails for role assignment. */
const EXECUTIVE_EMAILS = new Set(
  (process.env.EXECUTIVE_EMAILS ?? "")
    .split(",")
    .map((e) => e.trim().toLowerCase())
    .filter(Boolean)
);

/**
 * Build the headers object for gateway proxy calls.
 * Always includes the internal Bearer token. When an authenticated session
 * exists, also forwards X-User-Email and X-User-Role so the gateway can
 * scope chat history, memory, and audit trails to the real user.
 */
async function buildGatewayHeaders(): Promise<Record<string, string>> {
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    Authorization: `Bearer ${INTERNAL_TOKEN}`,
  };
  try {
    const session = await auth();
    if (session?.user?.email) {
      headers["X-User-Email"] = session.user.email;
      const role = EXECUTIVE_EMAILS.has(session.user.email.toLowerCase())
        ? "executive"
        : "employee";
      headers["X-User-Role"] = role;
    }
  } catch (_e) {
    // auth() can throw if called outside a request context — fall back to
    // internal-only headers (backward-compatible with cron/CI callers).
  }
  return headers;
}

// ─── SSE helpers ─────────────────────────────────────────────────────────────

function sseHeaders(): HeadersInit {
  return {
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache, no-transform",
    Connection: "keep-alive",
    "X-Accel-Buffering": "no",
  };
}

function sseEvent(payload: Record<string, unknown>): Uint8Array {
  return new TextEncoder().encode(`data: ${JSON.stringify(payload)}\n\n`);
}

/** Parse an accumulated AG-UI tool-args JSON string into an object for the UI. */
function parseToolArgs(raw: string | undefined): Record<string, unknown> {
  if (!raw || !raw.trim()) return {};
  try {
    const parsed = JSON.parse(raw);
    return typeof parsed === "object" && parsed !== null
      ? (parsed as Record<string, unknown>)
      : { value: parsed };
  } catch (_e) {
    // Streamed args may be incomplete/non-JSON — surface the raw text.
    return { _raw: raw };
  }
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest): Promise<Response> {
  let body: ChatRequest;
  try {
    body = (await req.json()) as ChatRequest;
  } catch (_e) {
    return new Response(
      `data: ${JSON.stringify({ type: "error", content: "Invalid JSON body" })}\n\n`,
      { status: 400, headers: sseHeaders() }
    );
  }

  const { agentName, message, messages, threadId, mode, model, context, thinkMode, assistantMessageId, lastEventId, reconnect } = body;
  if (!agentName || !message) {
    return new Response(
      `data: ${JSON.stringify({ type: "error", content: "agentName and message are required" })}\n\n`,
      { status: 400, headers: sseHeaders() }
    );
  }

  // ── Reconnect path: resume an existing agent stream after disconnect ────
  // When the frontend detects an interrupted stream on mount, it sends
  // reconnect=true with the last known event ID.  The gateway replays
  // missed events from Redis and continues with live events if the agent
  // is still running.
  if (reconnect && threadId) {
    const since = lastEventId || "0-0";
    let reconRes: Response;
    try {
      reconRes = await fetch(
        `${GATEWAY_URL}/agent/run/${encodeURIComponent(threadId)}/reconnect?since=${encodeURIComponent(since)}`,
        {
          method: "GET",
          headers: await buildGatewayHeaders(),
          signal: AbortSignal.timeout(310_000),
        },
      );
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return new Response(
        `data: ${JSON.stringify({ type: "error", content: `Reconnect failed: ${msg}` })}\n\n`,
        { status: 502, headers: sseHeaders() },
      );
    }
    if (!reconRes.ok || !reconRes.body) {
      const text = await reconRes.text().catch(() => `status ${reconRes.status}`);
      return new Response(
        `data: ${JSON.stringify({ type: "error", content: `Reconnect error: ${text}` })}\n\n`,
        { status: reconRes.status, headers: sseHeaders() },
      );
    }
    // Pass the reconnect stream through the same translation layer so the
    // frontend sees the same event format as a live stream.
    const reconStream = new ReadableStream<Uint8Array>({
      async start(controller) {
        await translateAndPersistStream(
          reconRes.body!, controller, threadId, assistantMessageId,
        );
      },
    });
    return new Response(reconStream, { headers: sseHeaders() });
  }

  // ── Gateway /v1 path: stream directly via litellm SDK ────────────────────
  // Routes to LiteLLM tier aliases (tier1/2/3 are cost-optimized tiers).
  // Backend can optionally route tiers through Copilot, Claude, GPT-4, or Gemini
  // (see infra/litellm/config.yaml for current routing).
  if (mode === "litellm") {
    return streamLiteLLM({ message, messages, model, context });
  }

  // ── Copilot/AG-UI path — ORCHESTRATOR ONLY ────────────────────────────────
  // The /copilot/chat endpoint is hardwired at gateway startup to the single
  // built-in orchestrator agent. Named agents (task-manager, sales-assistant,
  // any GitHub-registered agent) must go through /agent/run so the executor
  // can clone the repo, import agents.py, resolve integrations, and run via MAF.
  const ORCHESTRATOR_NAMES = new Set(["orchestrator", "default", "commandcenter", ""]);
  const isOrchestrator = ORCHESTRATOR_NAMES.has(agentName.toLowerCase().trim());

  if (mode === "copilot" && isOrchestrator) {
    let gatewayRes: Response;
    try {
      // AG-UI protocol: the current message must be part of the messages array.
      // Append it after the history so the agent sees the full conversation.
      const agUiMessages = [
        ...(messages ?? []).map((m) => ({ role: m.role, content: m.content })),
        { role: "user" as const, content: message },
      ];
      gatewayRes = await fetch(`${GATEWAY_URL}/copilot/chat`, {
        method: "POST",
        headers: await buildGatewayHeaders(),
        body: JSON.stringify({
          thread_id: threadId ?? "",
          messages: agUiMessages,
          think_mode: thinkMode ?? "auto",
        }),
        signal: AbortSignal.timeout(310_000),
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return new Response(
        `data: ${JSON.stringify({ type: "error", content: `Gateway unreachable: ${msg}` })}\n\n`,
        { status: 502, headers: sseHeaders() }
      );
    }
    if (!gatewayRes.ok || !gatewayRes.body) {
      const text = await gatewayRes.text().catch(() => `status ${gatewayRes.status}`);
      return new Response(
        `data: ${JSON.stringify({ type: "error", content: text })}\n\n`,
        { status: gatewayRes.status, headers: sseHeaders() }
      );
    }
    // Translate AG-UI → frontend SSE, persisting to Postgres so messages
    // survive client disconnect (tab close, browser quit, network drop).
    const translated = new ReadableStream<Uint8Array>({
      async start(controller) {
        await translateAndPersistStream(gatewayRes.body!, controller, threadId ?? "", assistantMessageId);
      },
    });
    return new Response(translated, { headers: sseHeaders() });
  }

  // ── Executor path: named agents (copilot mode) + langgraph mode ──────────
  // Named agents (copilot mode): route through /agent/run/stream which returns
  // a real AG-UI SSE stream so the UI sees tool events live.
  // Legacy langgraph mode: falls back to batch /agent/run (no streaming).
  if (mode === "copilot" && !isOrchestrator) {
    // /agent/run/stream returns the same AG-UI event format as /copilot/chat.
    let streamRes: Response;
    try {
      streamRes = await fetch(`${GATEWAY_URL}/agent/run/stream`, {
        method: "POST",
        headers: await buildGatewayHeaders(),
        body: JSON.stringify({
          agent: agentName,
          payload: { mode: "chat", message, messages: messages ?? [], think_mode: thinkMode ?? "auto" },
          thread_id: threadId ?? undefined,
          model: model ?? undefined,
        }),
        signal: AbortSignal.timeout(310_000),
      });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return new Response(
        `data: ${JSON.stringify({ type: "error", content: `Gateway unreachable: ${msg}` })}\n\n`,
        { status: 502, headers: sseHeaders() }
      );
    }
    if (!streamRes.ok || !streamRes.body) {
      const text = await streamRes.text().catch(() => `status ${streamRes.status}`);
      return new Response(
        `data: ${JSON.stringify({ type: "error", content: text })}\n\n`,
        { status: streamRes.status, headers: sseHeaders() }
      );
    }
    // Translate AG-UI → frontend SSE, persisting to Postgres so messages
    // survive client disconnect (tab close, browser quit, network drop).
    const translated2 = new ReadableStream<Uint8Array>({
      async start(controller) {
        await translateAndPersistStream(streamRes.body!, controller, threadId ?? "", assistantMessageId);
      },
    });
    return new Response(translated2, { headers: sseHeaders() });
  }

  // ── Legacy executor path: batch /agent/run (langgraph mode + fallback) ─
  // Used for langgraph mode. Returns a single delta+done SSE pair.
  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        const gatewayRes = await fetch(`${GATEWAY_URL}/agent/run`, {
          method: "POST",
          headers: await buildGatewayHeaders(),
          body: JSON.stringify({
            agent: agentName,
            payload: { mode: "chat", message, messages: messages ?? [] },
            thread_id: threadId ?? undefined,
          }),
          signal: AbortSignal.timeout(310_000),
        });

        if (!gatewayRes.ok) {
          const text = await gatewayRes.text().catch(() => `status ${gatewayRes.status}`);
          controller.enqueue(sseEvent({ type: "error", content: `Gateway error: ${text}` }));
          controller.close();
          return;
        }

        const data = (await gatewayRes.json()) as {
          run_id: string;
          agent: string;
          status: string;
          result?: unknown;
          error?: string;
          mutation_pr?: string;
        };

        // Normalise to string
        let content: string;
        if (data.status === "failed") {
          content = data.error
            ? `Agent run failed: ${data.error}${data.mutation_pr ? `\n\nA fix PR has been opened: ${data.mutation_pr}` : ""}`
            : "Agent run failed with an unknown error.";
        } else if (typeof data.result === "string") {
          content = data.result;
        } else if (data.result && typeof data.result === "object" && "content" in (data.result as object)) {
          content = String((data.result as { content: unknown }).content);
        } else {
          content = JSON.stringify(data.result, null, 2);
        }

        // Strip integration setup tokens before emitting
        const setupTokenRegex = /<<<SETUP:([^:]+):([A-Z0-9_]+)=([^>]+)>>>/g;
        const rawMatches: Array<{ service: string; key: string; value: string }> = [];
        let m: RegExpExecArray | null;
        while ((m = setupTokenRegex.exec(content)) !== null) {
          rawMatches.push({ service: m[1], key: m[2], value: m[3].trim() });
        }
        if (rawMatches.length > 0) {
          content = content.replace(/<<<SETUP:[^>]+>>>/g, "").trim();
          const vars = rawMatches.filter((x) => x.value).map((x) => ({ key: x.key, value: x.value }));
          if (vars.length > 0) {
            fetch(`${GATEWAY_URL}/integrations/configure`, {
              method: "POST",
              headers: await buildGatewayHeaders(),
              body: JSON.stringify({ vars }),
            }).catch(() => {});
          }
        }

        controller.enqueue(sseEvent({ type: "delta", content }));
        controller.enqueue(sseEvent({ type: "done", run_id: data.run_id }));
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        controller.enqueue(sseEvent({ type: "error", content: msg }));
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, { headers: sseHeaders() });
}

// ─── Gateway /v1 streaming (litellm SDK) ─────────────────────────────────────
// Streams an OpenAI-compatible chat completion from the gateway /v1 and
// re-emits it in our SSE format (delta / done / error). Enables the unified
// chat window to use any LiteLLM model alias (tier1/2/3, copilot/*).

function streamLiteLLM({
  message,
  messages,
  model,
  context,
}: {
  message: string;
  messages: ChatMessage[];
  model?: string;
  context?: string;
}): Response {
  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        const history = (messages ?? [])
          .filter((m) => m.role === "user" || m.role === "assistant")
          .map((m) => ({ role: m.role, content: m.content }));

        const chatMessages: { role: string; content: string }[] = [];
        if (context?.trim()) {
          chatMessages.push({
            role: "system",
            content: context.trim(),
          });
        }
        // history already includes the current user turn (appended client-side),
        // but guard against the last entry not being the current message.
        const hasCurrent =
          history.length > 0 &&
          history[history.length - 1].role === "user" &&
          history[history.length - 1].content === message;
        chatMessages.push(...history);
        if (!hasCurrent) chatMessages.push({ role: "user", content: message });

        const upstream = await fetch(`${LITELLM_BASE_URL}/chat/completions`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${LITELLM_KEY}`,
          },
          body: JSON.stringify({
            model: model ?? "tier2-sonnet",
            messages: chatMessages,
            stream: true,
          }),
          signal: AbortSignal.timeout(310_000),
        });

        if (!upstream.ok || !upstream.body) {
          const text = await upstream.text().catch(() => `status ${upstream.status}`);
          controller.enqueue(sseEvent({ type: "error", content: `LiteLLM error: ${text}` }));
          controller.close();
          return;
        }

        const reader = upstream.body.getReader();
        const decoder = new TextDecoder();
        let buffer = "";

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          buffer += decoder.decode(value, { stream: true });
          const lines = buffer.split("\n");
          buffer = lines.pop() ?? "";
          for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed.startsWith("data:")) continue;
            const raw = trimmed.slice(5).trim();
            if (!raw || raw === "[DONE]") continue;
            try {
              const json = JSON.parse(raw) as {
                choices?: {
                  delta?: {
                    content?: string;
                    // Reasoning / chain-of-thought fields used by thinking models:
                    //   • Gemini 2.5 thinking — "reasoning_content"
                    //   • Claude extended thinking (via LiteLLM) — "thinking_content"
                    //   • Some providers use "thinking"
                    reasoning_content?: string;
                    thinking_content?: string;
                    thinking?: string;
                  };
                }[];
              };
              const delta = json.choices?.[0]?.delta;
              if (!delta) continue;
              if (delta.content) {
                controller.enqueue(sseEvent({ type: "delta", content: delta.content }));
              }
              // Emit reasoning tokens so ThinkingContainer can show chain-of-thought.
              const reasoningDelta =
                delta.reasoning_content ?? delta.thinking_content ?? delta.thinking;
              if (reasoningDelta) {
                controller.enqueue(sseEvent({ type: "reasoning", content: reasoningDelta }));
              }
            } catch (_e) {
              // ignore non-JSON keep-alive lines
            }
          }
        }

        controller.enqueue(sseEvent({ type: "done" }));
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        controller.enqueue(sseEvent({ type: "error", content: `LiteLLM unreachable: ${msg}` }));
      } finally {
        controller.close();
      }
    },
  });

  return new Response(stream, { headers: sseHeaders() });
}
