"""skill-task-gtd — provider-agnostic GTD tools over the gateway /tasks API."""

from skill_task_gtd.core import (
    gtd_accounts,
    gtd_capture,
    gtd_capture_many,
    gtd_clarify,
    gtd_day_digest,
    gtd_estimate_stats,
    gtd_inbox_insights,
    gtd_list,
    gtd_list_projects,
    gtd_list_schedule,
    gtd_organize,
    gtd_people,
    gtd_plan_day,
    gtd_plan_project,
    gtd_replan_day,
    gtd_rollover,
    gtd_schedule,
    gtd_set_one_thing,
    gtd_sync,
    gtd_unschedule,
    gtd_update,
)

__all__ = [
    "gtd_accounts",
    "gtd_capture",
    "gtd_capture_many",
    "gtd_clarify",
    "gtd_day_digest",
    "gtd_estimate_stats",
    "gtd_inbox_insights",
    "gtd_list",
    "gtd_list_projects",
    "gtd_list_schedule",
    "gtd_organize",
    "gtd_people",
    "gtd_plan_day",
    "gtd_plan_project",
    "gtd_replan_day",
    "gtd_rollover",
    "gtd_schedule",
    "gtd_set_one_thing",
    "gtd_sync",
    "gtd_unschedule",
    "gtd_update",
]
