/**
 * The icon vocabulary.
 *
 * Lucide names are the canonical vocabulary the whole app speaks — they are
 * already used at ~160 call sites, they read semantically ("Trash2",
 * "AlertTriangle"), and keeping them means migrating a call site is a
 * one-token edit rather than learning a new naming scheme.
 *
 * Other packs map ONTO that vocabulary. `registry.json` is generated by
 * `scripts/build-icon-packs.mjs`, which resolves each name against the real
 * Fluent and Material Symbols collections so a mapping can never point at an
 * icon that does not exist.
 *
 * A name with no mapping for the active pack falls back to Lucide. That is
 * what makes the whole thing incrementally adoptable: agent-generated UI can
 * name any of Lucide's ~1,600 icons and still render, it just renders in the
 * base style until someone adds a mapping.
 */

import registryData from "./icon-data/registry.json";
import type { IconPackId } from "./types";

/** Per-pack icon name for one Lucide name. */
export type IconMapping = Partial<Record<Exclude<IconPackId, "lucide">, string>>;

export const ICON_REGISTRY = registryData as Record<string, IconMapping>;

/** Iconify collection prefix for each non-Lucide pack. */
const ICONIFY_PREFIX: Record<Exclude<IconPackId, "lucide">, string> = {
  fluent: "fluent",
  material: "material-symbols",
};

/**
 * Fully-qualified Iconify name (`"fluent:add-20-regular"`) for a Lucide name
 * in the given pack, or `null` when the pack is Lucide or has no mapping —
 * in which case the caller renders the Lucide glyph.
 */
export function iconifyName(lucideName: string, pack: IconPackId): string | null {
  if (pack === "lucide") return null;
  const mapped = ICON_REGISTRY[lucideName]?.[pack];
  return mapped ? `${ICONIFY_PREFIX[pack]}:${mapped}` : null;
}

/** Number of names carrying a mapping for `pack` — used by tests. */
export function mappedIconCount(pack: Exclude<IconPackId, "lucide">): number {
  return Object.values(ICON_REGISTRY).filter((m) => m[pack]).length;
}
