#!/usr/bin/env bash
# Dump the live Postgres schema to infra/postgres/schema.generated.sql.
#
# Why this exists
# ---------------
# The authoritative schema is spread across 40+ numbered migrations in
# infra/postgres/ — including renames and drops — so reconstructing the CURRENT
# shape of a table (e.g. "what columns does email_assistant_settings have?")
# means mentally replaying every migration that touched it. This script
# materialises a single consolidated, regenerable snapshot of the live schema so
# humans and AI dev agents can read the current shape in ONE file.
#
# The snapshot is GENERATED — never hand-edit it. To change the schema: add a
# numbered migration (NN_*.sql, idempotent), run scripts/apply_migrations.sh,
# then re-run this script to refresh the snapshot and commit it alongside the
# migration. See infra/postgres/README.md.
#
# Usage:  scripts/dump_schema.sh
# Env:    APP_DIR (default: repo root), PG_CONTAINER (default: acb-postgres)
set -euo pipefail

# Default APP_DIR to the repo root (this script lives in <root>/scripts).
APP_DIR="${APP_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
PG_CONTAINER="${PG_CONTAINER:-acb-postgres}"
OUT="$APP_DIR/infra/postgres/schema.generated.sql"

# Pull DB credentials from .env when present, else fall back to compose defaults
# (mirrors scripts/apply_migrations.sh).
ENV_FILE="$APP_DIR/.env"
PG_USER="acb"
PG_DB="acb"
if [ -f "$ENV_FILE" ]; then
  PG_USER="$(grep -E '^POSTGRES_USER=' "$ENV_FILE" | tail -1 | cut -d= -f2- || true)"
  PG_DB="$(grep -E '^POSTGRES_DB=' "$ENV_FILE" | tail -1 | cut -d= -f2- || true)"
  PG_USER="${PG_USER:-acb}"
  PG_DB="${PG_DB:-acb}"
fi

if ! docker ps --format '{{.Names}}' | grep -qx "$PG_CONTAINER"; then
  echo "ERROR: Postgres container '$PG_CONTAINER' is not running." >&2
  exit 1
fi

printf "==> Dumping schema of db '%s' (container: %s)\n" "$PG_DB" "$PG_CONTAINER"

{
  echo "-- schema.generated.sql — GENERATED by scripts/dump_schema.sh. DO NOT EDIT."
  echo "-- Source of truth for the CURRENT schema shape; change it via a numbered"
  echo "-- migration in infra/postgres/, apply it, then re-run scripts/dump_schema.sh."
  echo "--"
  docker exec "$PG_CONTAINER" \
    pg_dump --schema-only --no-owner --no-privileges -U "$PG_USER" -d "$PG_DB"
} > "$OUT"

printf "==> Wrote %s (%s lines)\n" "$OUT" "$(wc -l < "$OUT")"
